### PR TITLE
Upgrade rest-client to 2.x

### PR DESCRIPTION
**Pull request by Xuhao**

### CODE REVIEW

**Comment by rockuw** [comment]
Thanks for the PR!

Could you please fix the CI failures? https://travis-ci.org/aliyun/aliyun-oss-ruby-sdk/jobs/249286707

One of the problems I found is the http stub should be changed:

```ruby
# now
stub_request(:put, "http://rubysdk-bucket.oss.aliyuncs.com/?acl=")

# should be
stub_request(:put, "http://rubysdk-bucket.oss.aliyuncs.com/?acl")
```

**Comment by Xuhao** [comment]
@rockuw Sure, I will fix it ASAP. Thanks for notice.

**Comment by Xuhao** [comment]
@rockuw Can you take a look at the PR?

**Comment by rockuw** [comment]
@Xuhao The PR looks good to me. 

Please follow [this link](https://cla-assistant.io/aliyun/aliyun-oss-ruby-sdk?pullRequest=46) to sign the CLA.

After that I will merge the PR.

**Comment by Xuhao** [comment]
@rockuw cool! Thanks!

**Comment by rockuw** [comment]
@Xuhao The test still fails: https://travis-ci.org/aliyun/aliyun-oss-ruby-sdk/jobs/251031203

Could you take a look at it?

**Pull request merged**
